mdss: fixed "header" missing
build can cause this error

In file included from drivers/video/msm/mdss/mdss_mdp_trace.h:260:0,
                 from drivers/video/msm/mdss/mdss_mdp.c:61:
include/trace/define_trace.h:79:43: fatal error: ./mdss_mdp_trace.h: No such file or directory
 #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)

the file is present, but is only a declaration error, so add it directly to fix

Signed-off-by: Emanuele Scarlata (Fenix46) <scarlataemanuele@gmail.com>