tty: serial_hs: fixed compiled error
Compilation cause this error

error: implicit declaration of function ‘pinctrl_select_state’ [-Werror=implicit-function-declaration]

adding missing header to fix this

Signed-off-by: Emanuele Scarlata (Fenix46) <scarlataemanuele@gmail.com>