ASoC: add "wcdcal-hwdep" driver for wcd9320 codecs
When build Hammerhead device "wcd9320" codecs
cause this error on end build:

sound/built-in.o: In function `taiko_codec_config_mad':
/home/fenix46/android/kernel/caf/sound/soc/codecs/wcd9320.c:2738: undefined reference to `wcdcal_get_fw_cal'
sound/built-in.o: In function `taiko_get_hwdep_fw_cal':
/home/fenix46/android/kernel/caf/sound/soc/codecs/wcd9320.c:6564: undefined reference to `wcdcal_get_fw_cal'
sound/built-in.o: In function `taiko_codec_enable_anc':
/home/fenix46/android/kernel/caf/sound/soc/codecs/wcd9320.c:3424: undefined reference to `wcdcal_get_fw_cal'
sound/built-in.o: In function `taiko_codec_probe':
/home/fenix46/android/kernel/caf/sound/soc/codecs/wcd9320.c:7100: undefined reference to `wcd_cal_create_hwdep'
Makefile:788: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 1

it is cause because is missing "wcdcal-hwdep" driver
so add it to fix the error

Signed-off-by: Emanuele Scarlata (Fenix46) <scarlataemanuele@gmail.com>