i2c-msm: fixed implicit error
build hammerhead can cause this error

drivers/i2c/busses/i2c-msm-v2.c: In function 'i2c_msm_rsrcs_gpio_pinctrl_init':
drivers/i2c/busses/i2c-msm-v2.c:3055:2: error: implicit declaration of function 'devm_pinctrl_get' [-Werror=implicit-function-declaration]
  ctrl->rsrcs.pinctrl = devm_pinctrl_get(ctrl->dev);

fixed adding missing header for "pinctrl"

Signed-off-by: Emanuele Scarlata (Fenix46) <scarlataemanuele@gmail.com>